version: "3"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: DBUsers12*
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: DBUsers12*
  backend:
    depends_on:
      - db
    build: ./backend/
    restart: always
    command: yarn dev
    volumes:
      - ./backend/:/srv/app/
    ports:
      - "3333:3333"
  frontend:
    build: ./frontend/
    restart: unless-stopped
    command: yarn build && yarn start
    ports: 
      - "80:80"
    depends_on:
      - backend
