version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbuser
      MYSQL_ROOT_PASSWORD: DBUsers12*
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: DBUsers12*
      MYSQL_ROOT_HOST: "%"
  backend:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    command: npm run dev
    volumes:
      - ./:/usr/app/
    ports:
      - "3333:3333"
